{% macro department_filter_list() %}
  {% set filter_list = [
    'HCM - Outsources (Mobile & Fullstack) - Mobile & Fullstack Team',
    'Da Nang-Outsources (Ruby Dept)',
    'HCM - Bizsystem Division',
    'ERP Division',
    'BrSE Department',
    'SSD - BA Team',
    'Comm Department',
    'R&D Department',
    'IID - Tech Support & R&D Department',
    'TIO - CloudOps Team',
    'R&D - AI Team (ĐN)',
    'Da Nang-Outsources Division',
    'Da Nang-Outsources (QM Dept)/QC Team',
    'G1 - Onsite',
    'Da Nang-Outsources (UIT Dept)',
    'G1 - BrSE',
    'R&D - HN',
    'DX - DEV Team',
    'BSD - Bizsystem (.NET)',
    'Da Nang - Comm Team',
    'HCM - BAC (Comm Team)',
    'R&D - (AI) HCM',
    'Da Nang - BrSE Dept',
    'HCM - QM (QC Team)',
    'BSD - SCD Department',
    'G1 - Business Unit 8',
    'BSD - PMO Dept',
    'Hue - BPO Team',
    'Ho Chi Minh Branch',
    'HCM - Bizsystem (Java Dept)',
    'Da Nang-Outsources (QM Dept)/QA Team',
    'HCM - BAC Department',
    'HCM - Bizsystem (Flutter)',
    'G1 - Business Unit 2',
    'HCM - QM Department',
    'BSD - Web Dept (Low-code Team)',
    'ERP - Project Team',
    'BSD - Web Dept (GMO Team)',
    'BSD - Bizsystem Department',
    'HCM - BAC (BA Team)',
    'GMO 1 Division',
    'BSD - Smartphone Department',
    'G1 - Business Unit 6',
    'BSD - Bizsystem (Java)',
    'Creative Department',
    'HCM - Enterprise Solutions Department',
    'TIO - CyberWatch Team',
    'HCM - Outsources (Web Dept) - PHP Team',
    'Hue Branch',
    'HCM - Outsources (Web Dept)',
    'ERP - Development Team',
    'G1 - Business Unit 1',
    'Technology Innovation Office',
    'HCM - BAC (BrSE Team)',
    'HCM - Outsources (Moblie & Fullstack Dept)',
    'Creative (HN)',
    'SAP Department',
    'BSD - Web Dept (Labo Team)',
    'Da Nang Branch',
    'ERP - BA Team',
    'HCM - QM (QA Team)',
    'HCM - Outsources (Web Dept) - FE Team',
    'Da Nang-Outsources (EC Solutions Dept)',
    'Da Nang-Outsources (QM Dept)',
    'BSD - QC Department',
    'BSD - Web Dept (Spot Team)',
    'HCM - Outsources Division'
] %}
  {{ return(filter_list) }}
{% endmacro %}