name: 'dwh_project'
version: '1.0.0'
config-version: 2

profile: 'dwh_project'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target/{{ target.name }}"
clean-targets:
  - "target/{{ target.name }}"
  - "dbt_packages"

models:
  dwh_project:
    dwh:
      materialized: table
    dtm:
      hr:
        schema: hr 
        +generate_schema_name: false
        materialized: table
      jira:
        schema: jira
        +generate_schema_name: false
        materialized: table
      public:
        schema: public
        +generate_schema_name: false
        materialized: table
      bi:
        schema: bi
        +generate_schema_name: false
        materialized: table
      dimension:
        schema: dimension
        +generate_schema_name: false
        materialized: table
      fact:
        schema: fact
        +generate_schema_name: false
        materialized: table
      bridge:
        schema: bridge
        +generate_schema_name: false
        materialized: table

snapshots:
  dwh_project:
    target_schema: snapshots_dwh 
    post-hook: 
      - "COMMIT"
      - "VACUUM ANALYZE {{ this }}"