{{ config(materialized='table') }}

SELECT
    a._id as id,
    a."staffCode" as staff_code,
    a."firstName" as first_name,
    a."middleName" as middle_name,
    a."lastName" as last_name,
    a."emailCompany" as email_company,
    a."emailPersonal" as email_personal,
    {{ safe_parse_multiple_dates('a."birthDay"') }} as birth_day,
    {{ safe_parse_multiple_dates('a."welcomeDay"') }} as welcome_day,
    {{ safe_parse_multiple_dates('a."welcomeDate"') }} as welcome_date,
    a.gender as gender,
    a."mobileCountryCode" as mobile_country_code,
    a.mobile as mobile,
    a."officeTel" as office_tel,
    a.address as address,
    a.note as note,
    a."userJobStatus" as user_job_status,
    a.status as status,
    a."order" as sort_order,
    a."isDeleted" as is_deleted,
    a."userObjId" as user_id,
    {{ safe_parse_timestamp('a."createdAt"') }} as created_at,
    a."createdBy" as created_by,
    {{ safe_parse_timestamp('a."updatedAt"') }} as updated_at,
    a."updatedBy" as updated_by,
    a."employeeID" as employee_id,
    a."flagCron" as flag_cron,
    {{ safe_parse_multiple_dates('a."officialDate"') }} as official_date,
    {{ safe_parse_multiple_dates('a."probationDate"') }} as probation_date,
    a."organizationUnitID" as organization_unit_id,
    a."organizationUnitName" as organization_unit_name,
    {{ safe_parse_multiple_dates('a."internDate"') }} as intern_date,
    a."dataType" as data_type,
    a."MISACode" as misa_code,
    a."calculateSeniority" as calculate_seniority,
    {{ safe_parse_multiple_dates('a."quitDate"') }} as quit_date,
    {{ safe_parse_multiple_dates('a."timekeepingDate"') }} as timekeeping_date,

    etl_datetime
FROM {{ source('create', 'stg_create_user_infos') }} a

